apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: keycloak-cert
          secret:
            secretName: argocd-keycloak-ca
      initContainers:
        - name: inject-keycloak-ca
          image: debian:bookworm-slim
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              apt-get update >/dev/null
              apt-get install -y --no-install-recommends ca-certificates >/dev/null
              mkdir -p /usr/local/share/ca-certificates
              cp /etc/keycloak-ca/ca.crt /usr/local/share/ca-certificates/keycloak.crt
              update-ca-certificates >/dev/null
          volumeMounts:
            - name: keycloak-cert
              mountPath: /etc/keycloak-ca
      containers:
        - name: argocd-server
          volumeMounts:
            - name: keycloak-cert
              mountPath: /etc/keycloak-ca