apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: 'role:readonly'
  
  policy.csv: |
    # Define roles
    # Admin role - full access to all projects and applications
    p, role:admin, applications, *, */*, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, accounts, *, *, allow
    
    # Viewer role - read-only access to all projects
    p, role:viewer, applications, get, */*, allow
    p, role:viewer, repositories, get, *, allow
    p, role:viewer, clusters, get, *, allow
    
    # DevTest Viewer - can only view DevTest project apps
    p, role:devtest-viewer, applications, get, devtest/*, allow
    p, role:devtest-viewer, applications, get, devtest, allow
    
    # Read-only role - minimal read access
    p, role:readonly, applications, get, */*, allow
    
    # Role bindings (will be populated by SSO integration)
    # Format: g, <sso-user-or-group>, <role-name>
    
    # Keycloak group mappings (uncomment after Keycloak SSO is configured)
    g, argocd-admins, role:admin
    g, argocd-viewers, role:viewer
    g, devtest-developers, role:devtest-viewer
    
    # Other SSO examples (LDAP, GitHub, etc.):
    # g, admin-group@yourdomain.com, role:admin
    # g, devtest-group@yourdomain.com, role:devtest-viewer
    # g, viewer-group@yourdomain.com, role:viewer

  # RBAC scopes - which claims in the JWT/SAML token to use for RBAC
  scopes: '[groups, email]'
