apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfb-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/gitops
    targetRevision: main
    path: cfb/helm
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
