apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/gitops
    targetRevision: HEAD
    path: hello/helm
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
