apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-alerts
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/amokscience/gitops
    targetRevision: main
    path: monitoring/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
